export const listSexPet = [
  { label: 'Fêmea', value: 'F' },
  { label: 'Macho', value: 'M' },
]

export const listColorsPet = [
  { value: 'Amarelo', label: 'Amarelo' },
  { value: 'Amarelo Claro', label: 'Amarelo Claro' },
  { value: 'Amarelo Escuro', label: 'Amarelo Escuro' },
  { value: 'Amarelo Manchado', label: 'Amarelo Manchado' },
  { value: 'Bege', label: 'Bege' },
  { value: 'Bege Claro', label: 'Bege Claro' },
  { value: 'Bege Escuro', label: 'Bege Escuro' },
  { value: 'Bege Manchado', label: 'Bege Manchado' },
  { value: 'Branco', label: 'Branco' },
  { value: 'Branco Malhado', label: 'Branco Malhado' },
  { value: 'Branco Listrado', label: 'Branco Listrado' },
  { value: 'Branco Mesclado', label: 'Branco Mesclado' },
  { value: 'Caramelo', label: 'Caramelo' },
  { value: 'Cinza', label: 'Cinza' },
  { value: 'Cinza Claro', label: 'Cinza Claro' },
  { value: 'Cinza Escuro', label: 'Cinza Escuro' },
  { value: 'Cinza Manchado', label: 'Cinza Manchado' },
  { value: 'Laranja', label: 'Laranja' },
  { value: 'Laranja Claro', label: 'Laranja Claro' },
  { value: 'Laranja Escuro', label: 'Laranja Escuro' },
  { value: 'Listrado', label: 'Listrado' },
  { value: 'Malhado', label: 'Malhado' },
  { value: 'Marrom', label: 'Marrom' },
  { value: 'Marrom Claro', label: 'Marrom Claro' },
  { value: 'Marrom Escuro', label: 'Marrom Escuro' },
  { value: 'Mesclado', label: 'Mesclado' },
  { value: 'Preto', label: 'Preto' },
  { value: 'Preto Malhado', label: 'Preto Malhado' },
  { value: 'Preto Listrado', label: 'Preto Listrado' },
  { value: 'Preto Mesclado', label: 'Preto Mesclado' },
  { value: 'Abricot ou Tricolor', label: 'Abricot ou Tricolor' },
  { value: 'Preto e Branco', label: 'Preto e Branco' },
]

export const listSpeciesPet = [
  { value: 'Caninos', label: 'Caninos' },
  { value: 'Coelhos', label: 'Coelhos' },
  { value: 'Equinos', label: 'Equinos' },
  { value: 'Felinos', label: 'Felinos' },
  { value: 'Primatas', label: 'Primatas' },
  { value: 'Suínos', label: 'Suínos' },
]

export const listBreedsDogs = [
  { value: 'Sem Raça Definida (SRD)', label: 'Sem Raça Definida (SRD)' },
  { value: 'Afegão ou Afghan Hound', label: 'Afegão ou Afghan Hound' },
  { value: 'Affenpinscher', label: 'Affenpinscher' },
  { value: 'Airedale Terrier', label: 'Airedale Terrier' },
  { value: 'Akita Americano', label: 'Akita Americano' },
  { value: 'Akita Inu ou Akita Japonês', label: 'Akita Inu ou Akita Japonês' },
  { value: 'Alano Espanhol', label: 'Alano Espanhol' },
  { value: 'American Staffordshire Terrier', label: 'American Staffordshire Terrier' },
  { value: 'American Water Spaniel', label: 'American Water Spaniel' },
  { value: 'Barbet', label: 'Barbet' },
  { value: 'Basenji', label: 'Basenji' },
  { value: 'Basset Azul da Gasconha', label: 'Basset Azul da Gasconha' },
  { value: 'Basset Fulvo da Bretanha', label: 'Basset Fulvo da Bretanha' },
  { value: 'Basset Hound', label: 'Basset Hound' },
  { value: 'Beagle', label: 'Beagle' },
  { value: 'Beagle Harrier', label: 'Beagle Harrier' },
  { value: 'Bearded Collie', label: 'Bearded Collie' },
  { value: 'Bedlington Terrier', label: 'Bedlington Terrier' },
  { value: 'Bernese Mountain Dog', label: 'Bernese Mountain Dog' },
  { value: 'Bichon Bolonhês', label: 'Bichon Bolonhês' },
  { value: 'Bichon Havanês', label: 'Bichon Havanês' },
  { value: 'Bichon Frisé', label: 'Bichon Frisé' },
  { value: 'Bichon Maltês', label: 'Bichon Maltês' },
  { value: 'Bloodhound', label: 'Bloodhound' },
  { value: 'Boiadeiro Australiano', label: 'Boiadeiro Australiano' },
  { value: 'Boiadeiro Bernês', label: 'Boiadeiro Bernês' },
  { value: 'Border Collie', label: 'Border Collie' },
  { value: 'Border Terrier', label: 'Border Terrier' },
  { value: 'Borzoi', label: 'Borzoi' },
  { value: 'Boston Terrier', label: 'Boston Terrier' },
  { value: 'Boxer', label: 'Boxer' },
  { value: 'Bull Terrier', label: 'Bull Terrier' },
  { value: 'Buldogue ou Bulldog Inglês', label: 'Buldogue ou Bulldog Inglês' },
  { value: 'Buldogue ou Bullgod Francês', label: 'Buldogue ou Bullgod Francês' },
  { value: 'Bullmastiff ou Bulmastife', label: 'Bullmastiff ou Bulmastife' },
  { value: 'Cairn Terrier', label: 'Cairn Terrier' },
  { value: 'Cane Corso', label: 'Cane Corso' },
  { value: 'Cão de Água Português', label: 'Cão de Água Português' },
  { value: 'Cão de Crista Chinês', label: 'Cão de Crista Chinês' },
  { value: 'Cão de Montanha dos Pirinéus', label: 'Cão de Montanha dos Pirinéus' },
  { value: 'Cão lobo checoslovaco', label: 'Cão lobo checoslovaco' },
  { value: 'Cão da Groenlândia', label: 'Cão da Groenlândia' },
  { value: 'Caniche ou Poodle', label: 'Caniche ou Poodle' },
  { value: 'Cavalier King Charles Spaniel', label: 'Cavalier King Charles Spaniel' },
  { value: 'Chesapeake Bay Retriever', label: 'Chesapeake Bay Retriever' },
  { value: 'Chihuahua', label: 'Chihuahua' },
  { value: 'Chow Chow', label: 'Chow Chow' },
  { value: 'Cirneco do Etna', label: 'Cirneco do Etna' },
  { value: 'Cocker Spaniel Americano', label: 'Cocker Spaniel Americano' },
  { value: 'Cocker Spaniel Inglês', label: 'Cocker Spaniel Inglês' },
  { value: 'Collie', label: 'Collie' },
  { value: 'Coton de Tuléar', label: 'Coton de Tuléar' },
  { value: 'Dachshund', label: 'Dachshund' },
  { value: 'Dálmata', label: 'Dálmata' },
  { value: 'Dandie Dinmont Terrier', label: 'Dandie Dinmont Terrier' },
  { value: 'Doberman', label: 'Doberman' },
  { value: 'Dogue Alemão', label: 'Dogue Alemão' },
  { value: 'Dogue ou Dogo Argentino', label: 'Dogue ou Dogo Argentino' },
  { value: 'Dogue Canário', label: 'Dogue Canário' },
  { value: 'Dogue de Bordeaux', label: 'Dogue de Bordeaux' },
  { value: 'Elkhound Norueguês', label: 'Elkhound Norueguês' },
  { value: 'Fila Brasileiro', label: 'Fila Brasileiro' },
  { value: 'Fox Terrier', label: 'Fox Terrier' },
  { value: 'Foxhound Inglês', label: 'Foxhound Inglês' },
  { value: 'Galgo Escocês', label: 'Galgo Escocês' },
  { value: 'Galgo Irlandês', label: 'Galgo Irlandês' },
  { value: 'Golden Retriever', label: 'Golden Retriever' },
  { value: 'Gos dAtura', label: 'Gos dAtura' },
  { value: 'Grande Boiadeiro Suíço', label: 'Grande Boiadeiro Suíço' },
  { value: 'Greyhound ou Galgo Inglês', label: 'Greyhound ou Galgo Inglês' },
  { value: 'Grifo da Bélgica', label: 'Grifo da Bélgica' },
  { value: 'Husky Siberiano', label: 'Husky Siberiano' },
  { value: 'Jack Russel Terrier', label: 'Jack Russel Terrier' },
  { value: 'King Charles', label: 'King Charles' },
  { value: 'Komondor', label: 'Komondor' },
  { value: 'Kuvasz', label: 'Kuvasz' },
  { value: 'Labradoodle', label: 'Labradoodle' },
  { value: 'Labrador Retriever', label: 'Labrador Retriever' },
  { value: 'Laika', label: 'Laika' },
  { value: 'Lakeland Terrier', label: 'Lakeland Terrier' },
  { value: 'Leonberger', label: 'Leonberger' },
  { value: 'Lhasa Apso', label: 'Lhasa Apso' },
  { value: 'Malamute-do-Alasca', label: 'Malamute-do-Alasca' },
  { value: 'Maltês', label: 'Maltês' },
  { value: 'Mastife', label: 'Mastife' },
  { value: 'Mastin dos Pirenéus', label: 'Mastin dos Pirenéus' },
  { value: 'Mastin Espanhol', label: 'Mastin Espanhol' },
  { value: 'Mastin Napolitano', label: 'Mastin Napolitano' },
  { value: 'Norfolk Terrier', label: 'Norfolk Terrier' },
  { value: 'Norwich Terrier', label: 'Norwich Terrier' },
  { value: 'Old English ', label: 'Old English ' },
  { value: 'Papillon', label: 'Papillon' },
  { value: 'Pastor Alemão', label: 'Pastor Alemão' },
  { value: 'Pastor Australiano', label: 'Pastor Australiano' },
  { value: 'Pastor Belga', label: 'Pastor Belga' },
  { value: 'Pastor de Brie', label: 'Pastor de Brie' },
  { value: 'Pastor dos Pirenéus de Cara Rosa', label: 'Pastor dos Pirenéus de Cara Rosa' },
  { value: 'Pequeno Cão Leão', label: 'Pequeno Cão Leão' },
  { value: 'Pequinês', label: 'Pequinês' },
  { value: 'Perdigueiro', label: 'Perdigueiro' },
  { value: 'Pinscher miniatura', label: 'Pinscher miniatura' },
  { value: 'Pitbull', label: 'Pitbull' },
  { value: 'Podengo', label: 'Podengo' },
  { value: 'Poodle', label: 'Poodle' },
  { value: 'Pointer', label: 'Pointer' },
  { value: 'Pug', label: 'Pug' },
  { value: 'Rhodesian Ridgeback', label: 'Rhodesian Ridgeback' },
  { value: 'Rottweiler', label: 'Rottweiler' },
  { value: 'Rough Collie', label: 'Rough Collie' },
  { value: 'Sabueso ', label: 'Sabueso ' },
  { value: 'Saluki', label: 'Saluki' },
  { value: 'Samoieda', label: 'Samoieda' },
  { value: 'São Bernardo', label: 'São Bernardo' },
  { value: 'Scottish Terrier', label: 'Scottish Terrier' },
  { value: 'Setter Irlandês', label: 'Setter Irlandês' },
  { value: 'Shar-Pei', label: 'Shar-Pei' },
  { value: 'Shiba Inu', label: 'Shiba Inu' },
  { value: 'Shih Tzu', label: 'Shih Tzu' },
  { value: 'SilKy Terrier', label: 'SilKy Terrier' },
  { value: 'Skye Terrier', label: 'Skye Terrier' },
  { value: 'Smooth Collie', label: 'Smooth Collie' },
  { value: 'Spitz Alemão', label: 'Spitz Alemão' },
  { value: 'Spitz Alemão - Spitz Lobo', label: 'Spitz Alemão - Spitz Lobo' },
  { value: 'Spitz Alemão - Spitz Gigante', label: 'Spitz Alemão - Spitz Gigante' },
  { value: 'Spitz Alemão - Spitz Médio', label: 'Spitz Alemão - Spitz Médio' },
  { value: 'Spitz Alemão - Spitz Pequeno', label: 'Spitz Alemão - Spitz Pequeno' },
  { value: 'Spitz Alemão - Spitz Anão', label: 'Spitz Alemão - Spitz Anão' },
  { value: 'Spitz Alemão - Lulu da Pomerânia', label: 'Spitz Alemão - Lulu da Pomerânia' },
  { value: 'Staffordsgire Bull Terrier', label: 'Staffordsgire Bull Terrier' },
  { value: 'Tamaskan', label: 'Tamaskan' },
  { value: 'Teckel', label: 'Teckel' },
  { value: 'Terra Nova', label: 'Terra Nova' },
  { value: 'Terrier Australiano', label: 'Terrier Australiano' },
  { value: 'Terrier Escocês', label: 'Terrier Escocês' },
  { value: 'Terrier Irlandês', label: 'Terrier Irlandês' },
  { value: 'Terrier Japonês', label: 'Terrier Japonês' },
  { value: 'Terrier Negro Russo', label: 'Terrier Negro Russo' },
  { value: 'Terrier Norfolk', label: 'Terrier Norfolk' },
  { value: 'Terrier Norwich', label: 'Terrier Norwich' },
  { value: 'Terrier Tibetano', label: 'Terrier Tibetano' },
  { value: 'Tosa', label: 'Tosa' },
  { value: 'Weimaraner', label: 'Weimaraner' },
  { value: 'Welsh Corgi', label: 'Welsh Corgi' },
  { value: 'West Highland White Terrier', label: 'West Highland White Terrier' },
  { value: 'Whippet', label: 'Whippet' },
  { value: 'Xoloitzcuintli ', label: 'Xoloitzcuintli ' },
  { value: 'Yorkshire Terrier', label: 'Yorkshire Terrier' },
  { value: 'Miniature Schnauzer', label: 'Miniature Schnauzer' },
  { value: 'Schnauzer', label: 'Schnauzer' },
  { value: 'Giant Schnauzer', label: 'Giant Schnauzer' },
  { value: 'Terrier Brasileiro', label: 'Terrier Brasileiro' },
  { value: 'Kelpie Australiano', label: 'Kelpie Australiano' },
  { value: 'Galgo Italiano', label: 'Galgo Italiano' },
  { value: 'Sheltie', label: 'Sheltie' },
  { value: 'Pastor de Shetland', label: 'Pastor de Shetland' },
  { value: 'American Bully', label: 'American Bully' },
  { value: 'American Bull', label: 'American Bull' },
  { value: 'Biewer Terrier', label: 'Biewer Terrier' },
]

export const listBreedsRabbits = [
  { value: 'Sem Raça Definida (SRD)', label: 'Sem Raça Definida (SRD)' },
  { value: 'Anão Holandês ou Netherland Dwarf', label: 'Anão Holandês ou Netherland Dwarf' },
  { value: 'Argente Bleu', label: 'Argente Bleu' },
  { value: 'Argente Brun', label: 'Argente Brun' },
  { value: 'Beveren', label: 'Beveren' },
  { value: 'Branco de Florida', label: 'Branco de Florida' },
  { value: 'Britannia Petite', label: 'Britannia Petite' },
  { value: 'Coelho Alaska', label: 'Coelho Alaska' },
  { value: 'Coelho Americano', label: 'Coelho Americano' },
  { value: 'Califórnia', label: 'Califórnia' },
  { value: 'Canela ou Cinnamom', label: 'Canela ou Cinnamom' },
  { value: 'DArgente de Nata', label: 'DArgente de Nata' },
  { value: 'DArgente de Champagne', label: 'DArgente de Champagne' },
  { value: 'English Spot', label: 'English Spot' },
  { value: 'Fuzzy Lop Americano', label: 'Fuzzy Lop Americano' },
  { value: 'Giganta Britânico', label: 'Giganta Britânico' },
  { value: 'Gigante de Checkered', label: 'Gigante de Checkered' },
  { value: 'Gigante Flemish ou Flamengo', label: 'Gigante Flemish ou Flamengo' },
  { value: 'Hare Belgas', label: 'Hare Belgas' },
  { value: 'Harlequin', label: 'Harlequin' },
  { value: 'Havana', label: 'Havana' },
  { value: 'Holandês', label: 'Holandês' },
  { value: 'Hotot Anão', label: 'Hotot Anão' },
  { value: 'Jersey Wooly', label: 'Jersey Wooly' },
  { value: 'Lilac', label: 'Lilac' },
  { value: 'Lionhead', label: 'Lionhead' },
  { value: 'Lop', label: 'Lop' },
  { value: 'Lustrador', label: 'Lustrador' },
  { value: 'Mini Lop', label: 'Mini Lop' },
  { value: 'Mini Rex', label: 'Mini Rex' },
  { value: 'Mini Teddy', label: 'Mini Teddy' },
  { value: 'Nova Zelândia', label: 'Nova Zelândia' },
  { value: 'Palomino', label: 'Palomino' },
  { value: 'Pérola do Fumo', label: 'Pérola do Fumo' },
  { value: 'Prata', label: 'Prata' },
  { value: 'Raposa de Prata', label: 'Raposa de Prata' },
  { value: 'Raposa Suíça', label: 'Raposa Suíça' },
  { value: 'Rex', label: 'Rex' },
  { value: 'Rhinelander', label: 'Rhinelander' },
  { value: 'Sable Americano', label: 'Sable Americano' },
  { value: 'Satin', label: 'Satin' },
  { value: 'Siberiano', label: 'Siberiano' },
  { value: 'Sussex', label: 'Sussex' },
  { value: 'Tan', label: 'Tan' },
  { value: 'Thuringer', label: 'Thuringer' },
  { value: 'Viena', label: 'Viena' }
]

export const listBreedsHorses = [
  { value: 'Sem Raça Definida (SRD)', label: 'Sem Raça Definida (SRD)' },
  { value: 'Akhal-Teke', label: 'Akhal-Teke' },
  { value: 'Andalucian', label: 'Andalucian' },
  { value: 'Andaluz', label: 'Andaluz' },
  { value: 'Anglo-Árabe', label: 'Anglo-Árabe' },
  { value: 'Appaloosa', label: 'Appaloosa' },
  { value: 'Árabe', label: 'Árabe' },
  { value: 'Banker', label: 'Banker' },
  { value: 'Bashkir', label: 'Bashkir' },
  { value: 'Berbere', label: 'Berbere' },
  { value: 'Bretão', label: 'Bretão' },
  { value: 'Campeiro', label: 'Campeiro' },
  { value: 'Campolina', label: 'Campolina' },
  { value: 'Clydesdale', label: 'Clydesdale' },
  { value: 'Crioulo', label: 'Crioulo' },
  { value: 'Fjord', label: 'Fjord' },
  { value: 'Friesian', label: 'Friesian' },
  { value: 'Gypsy Vanner', label: 'Gypsy Vanner' },
  { value: 'Haflinger', label: 'Haflinger' },
  { value: 'Lavradeiro', label: 'Lavradeiro' },
  { value: 'Lusitano', label: 'Lusitano' },
  { value: 'Mangalarga', label: 'Mangalarga' },
  { value: 'Mangalarga Marchador', label: 'Mangalarga Marchador' },
  { value: 'Marajoara', label: 'Marajoara' },
  { value: 'Marwari', label: 'Marwari' },
  { value: 'Miniature', label: 'Miniature' },
  { value: 'Mustang', label: 'Mustang' },
  { value: 'Nordestino', label: 'Nordestino' },
  { value: 'Noriker', label: 'Noriker' },
  { value: 'Paint', label: 'Paint' },
  { value: 'Pampa', label: 'Pampa' },
  { value: 'Pantaneiro', label: 'Pantaneiro' },
  { value: 'Percheron', label: 'Percheron' },
  { value: 'Pônei Brasileiro', label: 'Pônei Brasileiro' },
  { value: 'Puro Sangue Inglês', label: 'Puro Sangue Inglês' },
  { value: 'Quarto de Milha', label: 'Quarto de Milha' },
  { value: 'Shetland', label: 'Shetland' },
  { value: 'Shire', label: 'Shire' },
  { value: 'Thoroughbred', label: 'Thoroughbred' },
]

export const listBreedsCats = [
  { value: 'Sem Raça Definida (SRD)', label: 'Sem Raça Definida (SRD)' },
  { value: 'Abissínio', label: 'Abissínio' },
  { value: 'Angorá Turco', label: 'Angorá Turco' },
  { value: 'Asiático de Pêlo Semi-Longo', label: 'Asiático de Pêlo Semi-Longo' },
  { value: 'Azul Russo', label: 'Azul Russo' },
  { value: 'Balinês', label: 'Balinês' },
  { value: 'Bambino', label: 'Bambino' },
  { value: 'Bicolor Oriental', label: 'Bicolor Oriental' },
  { value: 'Bengal', label: 'Bengal' },
  { value: 'Bobtail Americano', label: 'Bobtail Americano' },
  { value: 'Bobtail Japonês', label: 'Bobtail Japonês' },
  { value: 'Bombay', label: 'Bombay' },
  { value: 'Burmês ou Birmanês', label: 'Burmês ou Birmanês' },
  { value: 'Burmila', label: 'Burmila' },
  { value: 'California Spangled', label: 'California Spangled' },
  { value: 'Cingapura', label: 'Cingapura' },
  { value: 'Chartreux', label: 'Chartreux' },
  { value: 'Chausie', label: 'Chausie' },
  { value: 'Colorpoint de Pêlo Curto', label: 'Colorpoint de Pêlo Curto' },
  { value: 'Cornish Rex', label: 'Cornish Rex' },
  { value: 'Curl Americano', label: 'Curl Americano' },
  { value: 'Devon Rex', label: 'Devon Rex' },
  { value: 'Donskoy', label: 'Donskoy' },
  { value: 'Dragon Li', label: 'Dragon Li' },
  { value: 'Egeu', label: 'Egeu' },
  { value: 'Exótico Shorthair', label: 'Exótico Shorthair' },
  { value: 'Gato de Bengala', label: 'Gato de Bengala' },
  { value: 'Gato do Chipre', label: 'Gato do Chipre' },
  { value: 'Gato Asiático', label: 'Gato Asiático' },
  { value: 'Gabo Siberiano', label: 'Gabo Siberiano' },
  { value: 'Havana Marrom', label: 'Havana Marrom' },
  { value: 'Himalaio', label: 'Himalaio' },
  { value: 'Javanês', label: 'Javanês' },
  { value: 'Korat', label: 'Korat' },
  { value: 'Khao Manee', label: 'Khao Manee' },
  { value: 'Kurilian Bobtail', label: 'Kurilian Bobtail' },
  { value: 'LaPerm', label: 'LaPerm' },
  { value: 'Levkoy Ucraniano', label: 'Levkoy Ucraniano' },
  { value: 'Lykoi', label: 'Lykoi' },
  { value: 'Maine Coon', label: 'Maine Coon' },
  { value: 'Manx', label: 'Manx' },
  { value: 'Manx de Pêlo Longo', label: 'Manx de Pêlo Longo' },
  { value: 'Mau Árabe', label: 'Mau Árabe' },
  { value: 'Mau Egípcio', label: 'Mau Egípcio' },
  { value: 'MinsKin', label: 'MinsKin' },
  { value: 'Mist Australiano', label: 'Mist Australiano' },
  { value: 'Munchkin', label: 'Munchkin' },
  { value: 'Norueguês da Floresta', label: 'Norueguês da Floresta' },
  { value: 'Ocicat', label: 'Ocicat' },
  { value: 'Ojos Azules', label: 'Ojos Azules' },
  { value: 'Oregon Rex', label: 'Oregon Rex' },
  { value: 'Pêlo Curto Americano', label: 'Pêlo Curto Americano' },
  { value: 'Pêlo Curto Brasileiro', label: 'Pêlo Curto Brasileiro' },
  { value: 'Pêlo Curto Europeu', label: 'Pêlo Curto Europeu' },
  { value: 'Pêlo Curto Inglês ou British Shorthair', label: 'Pêlo Curto Inglês ou British Shorthair' },
  { value: 'Pêlo Longo Inglês', label: 'Pêlo Longo Inglês' },
  { value: 'Pêlo Curto Oriental', label: 'Pêlo Curto Oriental' },
  { value: 'Pêlo Logo Oriental', label: 'Pêlo Logo Oriental' },
  { value: 'Persa', label: 'Persa' },
  { value: 'Peterbald', label: 'Peterbald' },
  { value: 'Pixie-Bob', label: 'Pixie-Bob' },
  { value: 'Raas', label: 'Raas' },
  { value: 'Ragamuffin', label: 'Ragamuffin' },
  { value: 'Ragdoll', label: 'Ragdoll' },
  { value: 'Rex Alemão', label: 'Rex Alemão' },
  { value: 'Sagrado da Birmânia', label: 'Sagrado da Birmânia' },
  { value: 'Savannah', label: 'Savannah' },
  { value: 'Scottish Fold', label: 'Scottish Fold' },
  { value: 'Selkirk Rex', label: 'Selkirk Rex' },
  { value: 'Serengeti', label: 'Serengeti' },
  { value: 'Siamês', label: 'Siamês' },
  { value: 'Singapura', label: 'Singapura' },
  { value: 'Snowshoe', label: 'Snowshoe' },
  { value: 'Sokoke', label: 'Sokoke' },
  { value: 'Somali', label: 'Somali' },
  { value: 'Sphynx', label: 'Sphynx' },
  { value: 'Suphalak', label: 'Suphalak' },
  { value: 'Thai', label: 'Thai' },
  { value: 'Tiffany-Chantilly', label: 'Tiffany-Chantilly' },
  { value: 'Tonquinês', label: 'Tonquinês' },
  { value: 'Toyger', label: 'Toyger' },
  { value: 'Usuri', label: 'Usuri' },
  { value: 'Van Turco', label: 'Van Turco' },
  { value: 'Wirehair Americano', label: 'Wirehair Americano' }
]

export const listBreedsPrimates = [
  { value: 'Sem Raça Definida (SRD)', label: 'Sem Raça Definida (SRD)' },
  { value: 'Sagui', label: 'Sagui' },
  { value: 'Macaco-Prego', label: 'Macaco-Prego' }
]

export const listBreedsSwine = [
  { value: 'Sem Raça Definida (SRD)', label: 'Sem Raça Definida (SRD)' },
  { value: 'Mini Pug', label: 'Mini Pug' }
]
