const AMAZON_CREDENTIALS_ACCESS_KEY = process.env.NEXT_PUBLIC_AMAZON_CREDENTIALS_ACCESS_KEY
const AMAZON_CREDENTIALS_BUCKET = process.env.NEXT_PUBLIC_AMAZON_CREDENTIALS_BUCKET
const AMAZON_CREDENTIALS_REGION = process.env.NEXT_PUBLIC_AMAZON_CREDENTIALS_REGION
const AMAZON_CREDENTIALS_SECRET_KEY = process.env.NEXT_PUBLIC_AMAZON_CREDENTIALS_SECRET_KEY
const BASE_URL_BACKEND = process.env.NEXT_PUBLIC_BASE_URL_BACKEND
const FILES_URL = process.env.NEXT_PUBLIC_FILES_URL
const FILES_COMPRESSED_URL = process.env.NEXT_PUBLIC_COMPRESSED_FILES_URL
const GOOGLE_MAPS_API_KEY = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
const BASE_URL_WEB = process.env.NEXT_PUBLIC_BASE_URL_WEB

export {
  FILES_URL,
  FILES_COMPRESSED_URL,
  AMAZON_CREDENTIALS_ACCESS_KEY,
  AMAZON_CREDENTIALS_BUCKET,
  AMAZON_CREDENTIALS_REGION,
  AMAZON_CREDENTIALS_SECRET_KEY,
  BASE_URL_BACKEND,
  GOOGLE_MAPS_API_KEY,
  BASE_URL_WEB
}